### ISSUE TITLE
Statt weiterem Klick Bootstrap-Dropdown?

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/accessdenied#1]
![image](https://cloud.githubusercontent.com/assets/3855487/23969491/f39850ce-09c6-11e7-8280-3f2febb32c59.png)

Als Vorschlag... mit Symbol und Färbung logischerweise. Dann muss man nicht doppelt klicken und Ladezeit abwarten, um einen Status zu überspringen.

**Comment by hirbod** [comment]
Das ist über den EP leider nicht möglich.

**Comment by AWqxKAWERbXo** [comment]
Wäre es nicht möglich, das passende Fragment abzuwandeln und mitzuliefern?

**Comment by AWqxKAWERbXo** [comment]
@gharlan wäre es hier möglich, die Ausgabe in Structure zu verändern?

**Comment by gharlan** [comment]
https://github.com/FriendsOfREDAXO/accessdenied/blob/master/boot.php#L13

Da kann über `$subject[0][0] = ` der Name des Status 0 verändert werden.
