### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/accessdenied#12]
@staabm hast du ne Idee, wie man das hier ggf performanter machen könnte? Oder liefert Redaxo das aus dem Cache?

https://github.com/FriendsOfREDAXO/accessdenied/blob/7df1d64d8de53c468836cfc4e144c989d8c44a2e/boot.php#L21-L24

**Comment by staabm** [comment]
Gibts einen konkreten anlass oder ein Szenario das bekannt ist das es langsam ist?

**Comment by hirbod** [comment]
Ich habe nichts gemessen, aber ich habe das Gefühl, das alles etwas langsamer wird, sobald ich das AddOn aktiviere. Es ist nicht viel aber ein bisschen.

**Comment by staabm** [comment]
wenn konkret was messbares vorhanden ist, gerne wieder auf mich zukommen
