### ISSUE TITLE
css datei nur einbinden wenn verwendet

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/accessdenied#13]
aktuell wird die css datei dieses addons immer geladen:

https://github.com/FriendsOfREDAXO/accessdenied/blob/7df1d64d8de53c468836cfc4e144c989d8c44a2e/boot.php#L18

können wir hier ein IF drann packen, dass das ein wenig einschränkt?
brauchen wir das css wirklich auf _allen_ redaxo backend seiten?

**Comment by tbaddade** [comment]
Sollte das nicht eher in das QuickNavi-AddOn verschoben werden?

**Comment by staabm** [comment]
> Sollte das nicht eher in das QuickNavi-AddOn verschoben werden?

das quicknavi addon kann selbst bisher nicht entscheiden, wenn es einen status=2 gibt, ob dieser auch von accessdenied kommt, oder ggf. von einem anderen addon, was die gleiche ID nutzt

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/accessdenied/commit/b9b0d1c6db912389b332bfd61cdd246046645dc0
