### ISSUE TITLE
Error > 

### ISSUE THREAD

**Issue by Geri2017** [FriendsOfREDAXO/accessdenied#14]
Folgende Error Meldung:

> Error  | Call to a member function getValue() on null | redaxo/src/addons/accessdenied/boot.php | 23

REDAXO 5.7.0-beta2
PHP Version 7.2.11 
MySQL 5.6.19

Gibt es dafür eine Lösung?
Danke!
VG, Geri

**Comment by hirbod** [comment]
Hast du ein paar weitere Informationen für mich? Ich kann diesen Fehler nicht reproduzieren. Kann es sein, das noch keine Artikel und keine Kategorien angelegt sind?
