### ISSUE TITLE
YForm+URL-Kompatiblität

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/accessdenied#16]
Ich würde gerne auch bei aus YForm (optional mittels URL-Addon) generierten Seiten diese Funktion nutzen können, also sprich:
- gesperrt: leitet die URL zur Fehlerseite weiter - es sei denn, man ist im Backend angemeldet
- offline: lässt die Seite verfügbar
- online: alles wie immer

Lässt sich das mit accessdenied-Bordmitteln umsetzen? Gibt es eine Methode, der ich sagen kann: Wenn du 2 bist, dann nur im Backend eingeloggt anzeigen, sonst Weiterleitung zur Fehlerseite?

Ist das überhaupt hier in accessdenied gewünscht? Oder wäre so etwas eher ein Trick? 

Ein Automatismus / Einzeiler fürs Template fände ich am sinnvollsten hier aufgehoben.

**Comment by hirbod** [comment]
Ich hätte nicht dagegen, nur wüsste ich nicht, wie du das generisch abbilden möchtest. Klingt doch eher nach einem projektbezogenen Feature.

Das AddOn hier hängt sich nur in einen Struktur-EP und stellst einen weiteren Status zur Verfügung. Mehr macht es nicht.

Das AddOn müsste praktisch nen EP bereitstellen, um auf andere Bedürfnisse zu reagieren, z.B. einen Online-Status einer URL vom URL AddOn prüfen (dann muss jedoch sichergestellt werden, das die Tabelle ein Status-Feld hat  etc)

**Comment by hirbod** [comment]
Das ganze AddOn findet in diesen 4 Zeilen statt:
https://github.com/FriendsOfREDAXO/accessdenied/blob/master/boot.php#L22-L26

**Comment by schuer** [comment]
Close? @alexplusde @Hirbod

**Comment by AWqxKAWERbXo** [comment]
Ich glaube, ich muss dazu was im URL-Addon vorschlagen für Version 2. Da wäre es wohl am besten aufgehoben.
