### ISSUE TITLE
Browser URL ändert Status

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/accessdenied#17]
Folgendes Szenario das bei meinem Kunden zu irritationen führt:

1. Kunde ändert den Status eines Artikels.
2. Kunde klickt auf den Artikel.
3. Kunde nutzt den zurück Button im Browser. Nun wird ein anderer Status angezeigt als den, auf den er den Status des Artikels angepasst hat.

Warum? Die URL in der Browser Historie ruft erneut die Statusänderung auf. Lässt sich das verhindern?

**Comment by hirbod** [comment]
Ich denke das sinnvollste hier wäre, wenn man in irgend einer Form mit nem Token arbeiten würde. Ich hätte da auch eine Idee. Ich schau mal am Wochenende drüber

**Comment by TobiasKrais** [comment]
Danke! Redaxo arbeitet hier mit einer Weiterleitung nachdem der Status geändert wurde.

**Comment by AWqxKAWERbXo** [comment]
@TobiasKrais passiert das immernoch, seitdem es ein Dropdown ist?

**Comment by skerbis** [comment]
@alxndr-w ja , vorwärts / rückwärts im Browser ändern den status. Ist aber ein Core-Problem aus meiner Sicht.

**Comment by TobiasKrais** [comment]
Im Core wird das so gelöst, dass nach der Aktion eine Weiterleitung zur Seite gemacht wird. Das sollte hier im Addon auch so gemacht werden.

**Comment by TobiasKrais** [comment]
In der neuen 2.0.0-beta1 ist der Fehler behoben.

**Comment by skerbis** [comment]
kann ich nicht bestätigen
auch gibt es im core keine Weiterleitung
..  dieses AddOn kann das Verhalten aber auch nicht ändern, da es nur einen Status hinzufügt, mehr nicht. Es findet keine Verarbeitung statt.

**Comment by skerbis** [comment]
auch gibt es im core keine Weiterleitung
