### ISSUE TITLE
isPermitted() aufnehmen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/accessdenied#18]
https://github.com/tbaddade/redaxo_url/issues/158

muss das hier in diesem Addon gefixt werden?

**Comment by hirbod** [comment]
Hier kann ich nichts machen

**Comment by tbaddade** [comment]
Warum nicht? Dafür gibt es die Methode.

**Comment by hirbod** [comment]
Weil url doch bereits isOnline prüft. Und Value 2 gilt als offline.
