### ISSUE TITLE
Weiterleitungen prüfen

### ISSUE THREAD

**Issue by pschuchmann** [FriendsOfREDAXO/accessdenied#20]
Hi zusammen,

kurze Frage zu den Weiterleitungen von accessdenied. Wir haben gerade folgenden Fall, dass ein Kunde Weiterleitungen eines Artikels in yrewrite konfiguriert hat und den Artikel gesperrt hat. Es scheint so zu sein, dass die Umleitung auf die Fehlerseite durch accessdenied noch greift, bevor die konfigurierte Umleitung aus YRewrite zieht.

Zur eigentlichen Frage: Wäre es nicht sinnvoll, wenn accessdenied vor der Umleitung auf die Fehlerseite prüft, ob yrewrite vorhanden ist und gegebenfalls die Umleitung aus YRewrite greift?

**Comment by hirbod** [comment]
Interessanter Fall, ich kann mal schauen ob sowas performant machbar ist. Möchte ungerne weitere Anfragen an die DB schicken. Kann der Kunde nicht den Status einfach ändern, wenn sowieso weitergeleitet wird?

**Comment by pschuchmann** [comment]
Wir haben uns jetzt soweit hiermit beholfen, dass ist das angepasste Snippet aus der `boot.php`. Fürchte ohne DB Abfrage wird das kaum machbar sein. Oder man liest die die Forward Pathlist von yrewrite ein, aber könnte mir vorstellen, dass der SQL schneller durch ist.

```php
    if (rex_article::getCurrent() instanceof rex_article && 2 == rex_article::getCurrent()->getValue('status') && !rex_backend_login::hasSession()) {

      if (rex_addon::get('yrewrite')->isAvailable()) {
        
        $uri = rtrim($_SERVER['REQUEST_URI'], '/');
        $uri = ltrim($uri, '/');
        
        $sql = rex_sql::factory();
        $sql->setDebug(false);
        $sql->setQuery('SELECT * FROM '.rex::getTable('yrewrite_forward').' WHERE url = :url', ['url'=>$uri]);
        
        if ($sql->getRows()){
          
          if ($sql->getValue('id') != "") {
            
            if ($sql->getValue('type') == 'article') {
              $forward_url = rex_getUrl($sql->getValue('article_id'), $sql->getValue('clang'));
            } else if ($sql->getValue('type') == 'extern') {
              $forward_url = $sql->getValue('extern');
            }
            
            $movetype =  $sql->getValue('movetype');            
          }
          
        }       
        
        if ($forward_url != '') {
          //dump($forward_url );
          //dump($movetypes[$movetype] );
          header('HTTP/1.1 '.$movetypes[$movetype]);
          header('Location: ' . $forward_url);
          exit;
        }
        
      } else {
        rex_redirect(rex_article::getNotfoundArticleId(), rex_clang::getCurrentId());
      }
    }
```

Wenn wir den Status wieder auf online setzen, funktioniert auch der Redirect wieder, ja ;) Aber wenn er auch gesperrt noch funktioniert, wäre das ja auch nicht verkehrt. Das Issue sollte erstmal ein wenig Diskussion hervorbringen, was dann passiert, wird man ja sehen :)

**Comment by Hirbod** [comment]
Ich denke, in dem ganzen Code kannst du dir eigentlich den manuellen "Forward" sparen und yRewrite machen lassen. Finfach meinen rex_redirect nicht ausführen. Dann sollte das ganze ja "seinen eigentlichen Weg gehen"

**Comment by hirbod** [comment]
Ich denke, in dem ganzen Code kannst du dir eigentlich den manuellen "Forward" sparen und yRewrite machen lassen. Einfach meinen rex_redirect nicht ausführen. Dann sollte das ganze ja "seinen eigentlichen Weg gehen"

Die eigentlich Abfrage wäre (pseudo)
```php
// check if there is a redirect
$hasRedirect = true;
if(!$hasRedirect) {
        rex_redirect(rex_article::getNotfoundArticleId(), rex_clang::getCurrentId());
} else {
    // nix tun
}
```

P.S: wenn es ne Forward-Pathlist gibt, wäre diese aber schneller als DB, da das Array vermutlich schon im Memory liegt.

**Comment by pschuchmann** [comment]
Ok, hab eben nochmal geschaut, die liegt unter `\redaxo\cache\addons\yrewrite`. Schaue mir das nach dem Mittag nochmal an und melde mich nochmal. Wäre das denn interessant für einen PR, wenn es läuft?

**Comment by hirbod** [comment]
Denke schon. Einen Key in einem Array auf Existenz zu prüfen, sollte nicht zu teuer sein, da auch die Forward Pathlist meistens relativ klein ist. (vermute ich jetzt mal)

**Comment by pschuchmann** [comment]
Ok, das hab ich nun eben mal ein wenig getestet. YRewrite prüft auf jeden Fall nochmal die Domain ab und schiebt an dieser [Stelle](https://github.com/yakamara/redaxo_yrewrite/blob/master/lib/yrewrite/forward.php#L47) einen Riegel vor. 

Vielleicht kann @dergel noch kurz etwas dazu sagen, weshalb redaxointern Weiterleitungen nicht möglich sind. Mir ist klar, dass das ein großes Wirr Warr stiften kann, aber wäre nicht eine Weiterlung zu einem Inhaltsartikel schöner als der Redirect auf die Fehlerseite?

**Comment by pschuchmann** [comment]
@Hirbod Ich mache hier mal zu, ich glaube unser Fall war sehr speziell und hier hat sich sonst auch niemand mehr gemeldet.
