### ISSUE TITLE
Feature: Aufruf über secret oder Passwort ermöglichen. 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/accessdenied#25]
Update, es wurde ein neues AddOn, weil ich auch online / offline verändert habe. 
Meine Variante vererbt die Eigenschaft auch.  
https://github.com/KLXM/locked

**Comment by hirbod** [comment]
Ich hätte nichts dagegen gehabt, wenn das auch in dieses AddOn geflossen wäre. Jetzt gibts halt wieder nen zusätzliches AddOn, das ähnliche Features hat.

**Comment by skerbis** [comment]
@Hirbod ich habe Änderungen eingebracht, die zu langen Diskussionen geführt hätten. 
Die Änderung der Bezeichnungen für online/offline

**Comment by hirbod** [comment]
Vllt hast du ja lust das Preview-Feature zu portieren. Oder aber wir schreiben in die Readme, das es noch ein ähnliches AddOn gibt, das jedoch die Status-Namen verändert.

**Comment by skerbis** [comment]
@Hirbod ich mache einen PR. 
Ich lasse es erstmal beim Kunden testen 😀
Lang-Files muss ich auch noch anlegen

**Comment by skerbis** [comment]
@Hirbod könntest du dir vorstellen, dass beide AddOns im Maintenance-AddOn aufgehen?

**Comment by hirbod** [comment]
Ich muss mir das AddOn mal genauer anschauen und ob oder wie viel Overhead es mitbringt. Prinzipiell ist dieses AddOn hier schon sehr minimalistisch und genau auf einen Anwendungsbereich beschränkt. Weiß nicht ob’s klar und nicht verwirrend ist, wenn das Feature im maintenance untergeht. Falls du das Feature einbaust, würde ich das AddOn hier weiter bestehen lassen, aber es dann deaktivieren, falls dein AddOn installiert wird oder aktiviert ist, damit es nicht kollidiert.

**Comment by skerbis** [comment]
Ich sehe hier noch ein Problem. Wenn mein AddOn zu access denied  wird, dann verändern wir das Verhalten deines Addons, da meins den offline Status auf alle darunter liegenden Unterkategorien und Artikel vererbt. 
Das könnte für Unmut sorgen nach einem update.

Ich weiß nicht wie wir das abfangen können.

Ich will aber auch keine Settingsseite.

In meinem AddOn ist bereits eine conflict Regel eingebaut. So dass die beiden AddOns nicht gleichzeitig installiert sein können.

**Comment by hirbod** [comment]
Ok verstehe, deins ist schon etwas spezieller. Settings würde ich auch nicht einfügen wollen, verkompliziert eigentlich immer alles.

**Comment by skerbis** [comment]
Aber was du gebrauchen kannst, kannst du dir gerne mitnehmen 😉oder ich deinem per pr einreichen
