### ISSUE TITLE
Multi-Domain Artikelvorschau mittels secret unterstützen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/accessdenied#30]
* Link manipulieren
* Eingabe eines secrets (oder / und zusätzlich maintenance-secret verwenden können)

```
if(rex::isBackend() && rex_backend_login::hasSession() && 'content/edit' == rex_be_controller::getCurrentPage()) {
 
  rex_extension::register('URL_REWRITE', "url_rewrite_accessdenied", rex_extension::LATE);

}

function url_rewrite_accessdenied($ep) {
  $params = $ep->getParams();
 if(rex_article::get($params['id'])->getValue('status') == 2) {
  return $ep->getSubject().'?secret='.rex_config::get('accessdenied', 'secret');
 }
}
```

**Comment by skerbis** [comment]
Schau mal die Sharing-Lösung von Locked: https://github.com/klxm/locked @alxndr-w

**Comment by AWqxKAWERbXo** [comment]
Können wir locked und accessdenied nicht mittelfristig zusammenführen? Es gibt gefühlt eine Addon-Seuche mit Kleinstlösungen, die sich allesamt überschneiden.

**Comment by skerbis** [comment]
Klar gerne. An sich könnte es dieses AddOn voll und kompatibel ersetzen. 
Allerdings vererbt meins die Sperrung auf darunter liegende Kategorieren. Wenn das kein Problem darstellt könnte man beide zusammenführen.

**Comment by skerbis** [comment]
Sollte hiermit gehen: https://github.com/FriendsOfREDAXO/accessdenied/pull/32
