### ISSUE TITLE
Vorschau-Link kopierbar machen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/accessdenied#33]
![image](https://user-images.githubusercontent.com/3855487/171035993-964112cb-1369-486b-8787-48e3b5815f1c.png)

**Comment by skerbis** [comment]
<img width="386" alt="Bildschirmfoto 2022-05-30 um 20 19 05" src="https://user-images.githubusercontent.com/791247/171043807-32bc9429-4bee-4e1a-ba1f-f2aeb3a41890.png">

**Comment by AWqxKAWERbXo** [comment]
Ein Träumchen. Issues completed.
