### ISSUE TITLE
Sharing-Link zum Zugriff ohne angemeldeten Nutzer

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/accessdenied#35]
Coole Sache das Addon.
Toll wäre es noch, wenn man einen Sharing-Link (Hash) erstellen könnten, mit welchem man die jeweilige gesperrte Seite auch ohne Login anschauen könnte.

Das wäre ideal, um einem Kunden eine Änderung kurz zeigen zu können, welcher selber nicht in das Backend geht bzw. seine Seite pflegen lässt.

**Comment by skerbis** [comment]
jupp. Ist bereits integriert

**Comment by iceman-fx** [comment]
Wo finde ich das denn?
Oder ist dies in der Installerversion noch nicht drin?

**Comment by skerbis** [comment]
kommt gleich in Version 2.0
