### ISSUE TITLE
Online/Offline-Button bei gesperrten Artikeln ist weg nach Deinstallation des Addons

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/accessdenied#36]
Online/Offline-Button beim Artikel ist weg nachdem das Addon deinstalliert wurde und der Artikel vorher auf "gesperrt" gestellt war.

**Comment by skerbis** [comment]
Ok, das ist teils ein Core-Problem aber auch eins das hier im AddOn diskutiert werden muss. 

1. Der Core kennt den Status '2' nicht und zeigt daher keinen Namen. 
2. Soll der Status aller "offline" Artikel nach Deinstallation auf offline gestellt werden? 

@alxndr-w , was wollen wir machen?

**Comment by hirbod** [comment]
Alle gesperrten auf offline stellen, da es das nächstgelegene ist. Online bleibt online. 1 Zeiler sql + Cache clearen
