### ISSUE TITLE
Preview-Link: Zahlen und Sonderzeichen erlauben, ggf. Zufallswert setzen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/accessdenied#40]
https://github.com/FriendsOfREDAXO/accessdenied/blob/2d29f7d4d08e7cc70674a0ef208edd32d02c73a5/pages/system.accessdenied.php#L22

@skerbis siehst du da ein Problem, Zahlen und Sonderzeichen zuzulassen sowie bei der Installation eine zufällige Zeichenfolge zu setzen? 

Zumindest Zahlen sollten drin sein - so kann man das Feld wie ein Passwort behandeln und nicht bei beliebigen REDAXO-Seiten erraten, dass man mit `preview=1` an Daten rankommt, die eigentlich geschützt sind.

**Comment by skerbis** [comment]
nun ja .. wie der parameter heißt entscheidet ja der Admin. Kannst die Regel gerne erweitern. 
preview=1 ist eigentlich nicht möglich, man muss schon die ID des schützten Artikels kennen.
