### ISSUE TITLE
gesperrt auf "-1" stellen statt "2"

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/accessdenied#6]
Meines Erachtens ist eine Sperrung etwas, das weiter geht als offline schalten, und sollte demzufolge auch mit `status = -1` eingetragen werden.

**Comment by hirbod** [comment]
Ist nur etwas, was ich gar nicht steuern kann, da der Wert "2" vom System festgelegt wird.
