### ISSUE TITLE
Zusammenführen mit Structure Tweaks?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/accessdenied#7]

**Comment by skerbis** [comment]
dann bleibt's halt so

**Comment by tbaddade** [comment]
> dann bleibt's halt so

Weshalb?

**Comment by skerbis** [comment]
Der Lead ist ja dagegen s.o.

**Comment by hirbod** [comment]
Prinzipiell ist der Vorschlag gut, nur finde ich die Einfachheit von accessdenied so angenehm, da es auch keine Config hat und Plug n Play ist. Structure Tweaks bringt overhead mit, bin nicht sicher ob es da reingehört

**Comment by tbaddade** [comment]
Für mich passt es dort sehr gut mit hinein. Grad weil es innerhalb der Struktur kleine Anpassungen sind. Die Einstellungsseite gibt es dort bereits, so dass nur eine weitere Option wäre.

**Comment by hirbod** [comment]
Genau das ist (für mich) das Problem.
